stages:
  - lint
  - login
  - build
  - test

variables:
  CONTAINER_TEST_IMAGE: tol/tolid-api/tolid-api:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: tol/tolid-api/tolid-api:latest

lint:
  tags:
    - autoscale
  image: python:3.7
  stage: lint
  script:
    - pip install flake8
    - flake8 swagger_server/

login:
  tags:
    - autoscale
  image: docker:19.03.12-git
  stage: login
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  tags:
    - autoscale
  image: docker:18-git
  stage: build
  services:
    - docker:18-dind
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .

test:
  tags:
    - autoscale
  image: docker:18-git
  stage: test
  services:
    - docker:18-dind
  variables:
    POSTGRES_DB: tolid
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: runner
    POSTGRES_HOST_AUTH_METHOD: trust
    DB_URI: postgresql://runner:runner@db/tolid
    APP_URL: http://localhost:8080
  script:
    - docker network create -d bridge my-network
    - docker run --network my-network --name db --env POSTGRES_USER --env POSTGRES_PASSWORD --env POSTGRES_DB --env POSTGRES_HOST_AUTH_METHOD -dp 5432:5432 postgres:12
    - docker build -t andrew-tolid .
    - docker run --network my-network -dp 8080:8080 --env DB_URI --env APP_URL --name andrew-tolid andrew-tolid
    - docker exec andrew-tolid bash -c "pip3 install tox; tox"
