# This is used for local development only
version: '3.1'

services:
  tolid-db:
    image: postgres:11
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

  tolid-api:
    build: tolid-api/.
    image: tolid-api
    #command: python3 -m swagger_server
    environment:
      - DB_URI
    ports:
      - 8080:8080

  tolid-ui:
    build:
      context: tolid-ui/.
      dockerfile: Dockerfile.dev
    image: tolid-ui
    #command: python3 -m swagger_server
    stdin_open: true
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - './tolid-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'
    
  tolid-api-test:
    image: tolid-api
    command: dockerize
        -wait tcp://db:5432 -wait tcp://api:8080 -timeout 10s
        bash -c "pip3 install tox; tox"
    environment:
      DB_URI: ${DB_URI}
    depends_on:
      - tolid-db
      - tolid-api

  tolid-ui-test:
    image: tolid-ui
    command: yarn test
    stdin_open: true
    environment:
      - NODE_ENV=development
    volumes:
      - './tolid-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'
