version: '3.1'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  api:
    build: .
    image: api
    #command: python3 -m swagger_server
    environment:
      DB_URI: ${DB_URI}
    ports:
      - 8080:8080

  api-tests:
    image: api
    command: dockerize
        -wait tcp://db:5432 -wait tcp://api:8080 -timeout 10s
        bash -c "pip3 install tox; tox"
    environment:
      APP_URL: http://api:8080
      DB_URI: ${DB_URI}
    depends_on:
      - db
      - api