---
openapi: "3.0.0"
info:
  title: "Tree of Life public name API"
  description: "API for ToL Public name registry"
  contact:
    email: "kh14@sanger.ac.uk"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.0"
# servers:
# - url: "https://virtserver.swaggerhub.com/khaug/public-name/1.0.0"
#   description: "SwaggerHub API Auto Mocking"
tags:
- name: "curators"
  description: "Secured curator-only access"
- name: "consumers"
  description: "Browsing public names"
paths:
  /public-name:
    get:
      tags:
      - "consumers"
      summary: "searches DToL public names"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ public names in the system\n"
      operationId: "searchPublicName"
      parameters:
      - name: "searchString"
        in: "query"
        description: "pass an optional search string for looking up a public name"
        required: false
        style: "form"
        explode: true
        schema:
          type: "string"
      - name: "skip"
        in: "query"
        description: "number of records to skip for pagination"
        required: false
        style: "form"
        explode: true
        schema:
          minimum: 0
          type: "integer"
          format: "int32"
      - name: "limit"
        in: "query"
        description: "maximum number of records to return"
        required: false
        style: "form"
        explode: true
        schema:
          maximum: 10000000
          minimum: 0
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "search results matching criteria"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PublicName"
        "400":
          description: "bad input parameter"
    post:
      tags:
      - "curators"
      summary: "adds a public name"
      description: "Adds a new public name to the system"
      operationId: "addPublicName"
      requestBody:
        description: "Public name to add"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublicName"
      responses:
        "201":
          description: "item created"
        "400":
          description: "invalid input, object invalid"
        "409":
          description: "an existing item already exists"
components:
  schemas:
    PublicName:
      required:
      - "commonName"
      - "family"
      - "genus"
      - "order"
      - "phylum"
      - "prefix"
      - "species"
      - "taxID"
      - "taxaClass"
      type: "object"
      properties:
        prefix:
          type: "string"
          example: "a"
        species:
          type: "string"
          example: "Homo sapiens"
        taxID:
          type: "integer"
          example: 9606
        commonName:
          type: "string"
          example: "human"
        genus:
          type: "string"
          example: "Homo"
        family:
          type: "string"
          example: "Hominidae"
        order:
          type: "string"
          example: "Primates"
        taxaClass:
          type: "string"
          example: "Mammalia"
        phylum:
          type: "string"
          example: "Chordata"
