openapi: 3.0.0
info:
  title: Tree of Life public name API
  description: API for ToL Public name registry
  contact:
    email: kh14@sanger.ac.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.3.2
servers:
  - description: Tree of Life public name Swagger API
    url: http://0.0.0.0:8080
  - description: Tree of Life public name Swagger API 1.3.0
    url: http://0.0.0.0:8080/1.3.0
tags:
- name: curators
  description: Curator tools
- name: users
  description: Browsing public names
paths:
  /public-name:
    get:
      tags:
      - users
      summary: searches DToL public names
      description: |
        By passing in the appropriate options, you can search for
        available public names in the system. <b>prefix is the public name</b>
      operationId: search_public_name
      parameters:
      - name: taxonomyId
        in: query
        description: pass an NCBI taxonomy ID for looking up public name and taxonomy information
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: specimenId
        in: query
        description: pass a GAL specime ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicName'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.consumers_controller
    put:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: adds a public name
      description: Adds a new public name to the system
      operationId: add_public_name
      parameters:
      - name: taxonomyId
        in: query
        description: NCBI taxonomy ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: specimenId
        in: query
        description: specimen ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string  
      # requestBody:
      #   description: Public name to add
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/PublicName'
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.curators_controller
  /verify-database: 
    post:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: verifies and maintains database integrity
      description: Verifies and rebuilds the local database if required
      operationId: verify_database
      parameters:
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string 
      responses:
        "201":
          description: item created
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.curators_controller  
components:
  schemas:
    PublicName:
      required:
      - commonName
      - family
      - genus
      - order
      - phylum
      - prefix
      - publicName
      - species
      - taxID
      - taxaClass
      type: object
      properties:
        prefix:
          type: string
          example: mHomSap
        publicName:
          type: string
          example: mHomSap1
        species:
          type: string
          example: Homo sapiens
        taxID:
          type: integer
          example: 9606
        commonName:
          type: string
          example: human
        genus:
          type: string
          example: Homo
        family:
          type: string
          example: Hominidae
        order:
          type: string
          example: Primates
        taxaClass:
          type: string
          example: Mammalia
        phylum:
          type: string
          example: Chordata
      example:
        commonName: human
        publicName: mHomSap1
        phylum: Chordata
        species: Homo sapiens
        genus: Homo
        prefix: mHomSap
        taxID: 9606
        taxaClass: Mammalia
        family: Hominidae
        order: Primates
  securitySchemes:
    ApiKeyAuth:        # name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: api-key  # name of the header, query parameter or cookie
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.apikey_auth
# security:
#   - ApiKeyAuth: []     # 2) Apply the API key globally to all operations
  