openapi: 3.0.0
info:
  title: Tree of Life public name API
  description: API for ToL Public name registry
  contact:
    email: kh14@sanger.ac.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.5.0
servers:
  - url: http://0.0.0.0:8080/public_name_api
tags:
- name: curators
  description: Curator tools
- name: users
  description: Browsing public names
paths:
  /public-name:
    get:
      tags:
      - users
      summary: Search for a single public name
      description: |
        By passing in the appropriate options, you can search for
        available public names in the system.
      operationId: search_public_name
      parameters:
      - name: taxonomyId
        in: query
        description: pass an NCBI taxonomy ID for looking up public name and taxonomy information
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: specimenId
        in: query
        description: pass a GAL specime ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicName'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.consumers_controller
    post:
      security:
        - ApiKeyAuth: []
      tags:
      - users
      summary: Bulk search for public names
      description: |
        By passing in the appropriate options, you can search for
        available public names in the system. Public names will be
        created if new.
        ```
        [
          {"taxonomyId": 6344, "specimenId": "SAN0000100"},
          {"taxonomyId": 55617, "specimenId": "SAN0000101"}
        ]
        ```
      operationId: bulk_search_public_name
      parameters:
        - name: api-key
          in: header
          description: API-Key
          required: True
          style: simple
          explode: true
          schema:
            type: string  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxonSpecimen'
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicName'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.consumers_controller
    put:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: adds a public name
      description: Adds a new public name to the system
      operationId: add_public_name
      parameters:
      - name: taxonomyId
        in: query
        description: NCBI taxonomy ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: specimenId
        in: query
        description: specimen ID
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string  
      # requestBody:
      #   description: Public name to add
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/PublicName'
      responses:
        "200":
          description: item created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicName'
                x-content-type: application/json
        "400":
          description: invalid input, object invalid
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.curators_controller
  /public-name/all:
    get:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: List all assigned public names
      description: |
        Returns a list of all public names in the database
      operationId: list_public_names
      parameters:
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string  
      - name: taxonomyId
        in: query
        description: pass an NCBI taxonomy ID to filter results by
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: bad input parameter
        "403":
          description: user not authorised to use this function
      x-openapi-router-controller: swagger_server.controllers.curators_controller
  /species:
    get:
      tags:
      - users
      summary: Search for a single species
      description: |
        By passing in the appropriate options, you can search for
        available species in the system.
      operationId: search_species
      parameters:
      - name: taxonomyId
        in: query
        description: pass an NCBI taxonomy ID for looking up public name and taxonomy information
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Species'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.consumers_controller
    put:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: adds a species
      description: Adds a new species to the system
      operationId: add_species
      parameters:
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string  
      requestBody:
        description: Species to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Species'
      responses:
        "200":
          description: item created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Species'
                x-content-type: application/json
        "400":
          description: invalid input, object invalid
        "403":
          description: user not authorised to use this function
        "409":
          description: an existing item already exists
      x-openapi-router-controller: swagger_server.controllers.curators_controller
    patch:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: modifies a species
      description: Modifies an existing species, for example by changing the scientific name
      operationId: edit_species
      parameters:
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string  
      requestBody:
        description: Species to modify
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Species'
      responses:
        "200":
          description: item modified
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Species'
                x-content-type: application/json
        "400":
          description: invalid input, object invalid
        "403":
          description: user not authorised to use this function
        "409":
          description: item does not exist
      x-openapi-router-controller: swagger_server.controllers.curators_controller
  /species/all:
    get:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: List all species and their assigned prefixes
      description: |
        Returns a list of all species in the database
      operationId: list_species
      parameters:
      - name: api-key
        in: header
        description: API-Key
        required: True
        style: simple
        explode: true
        schema:
          type: string  
      responses:
        "200":
          description: search results matching criteria
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: bad input parameter
        "403":
          description: user not authorised to use this function
      x-openapi-router-controller: swagger_server.controllers.curators_controller
  /validate-manifest:
    post:
      security:
        - ApiKeyAuth: []
      tags:
      - curators
      summary: Validate an excel manifest
      description: |
        Validates an excel manifest and offers option to download manifest with public names filled in
      operationId: validate_manifest
      parameters:
        - name: api-key
          in: header
          description: API-Key
          required: True
          style: simple
          explode: true
          schema:
            type: string  
        - name: speciesColumnHeading
          in: query
          description: the column heading of the column containing the species name
          required: false
          style: form
          explode: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              x-body-name: excelFile
              type: object
              properties:
                excelFile:
                  type: string
                  format: binary
              required:
                - excelFile
      responses:
        "200":
          description: An Excel file, with the public names filled in
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
        "400":
          description: manifest has not validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageList'
      x-openapi-router-controller: swagger_server.controllers.curators_controller
components:
  schemas:
    TaxSpec:
      type: object
      required:
        - taxonomyId
        - specimenId
      properties:
        taxonomyId:
          type: integer
          example: 6344
        specimenId:
          type: string
          example: "SAN0000100"
    TaxonSpecimen:
      type: array
      items:
        $ref: '#/components/schemas/TaxSpec'
        required:
        - TaxSpec
    PublicName:
      required:
        - commonName
        - family
        - genus
        - order
        - phylum
        - kingdom
        - prefix
        - publicName
        - species
        - taxonomyId
        - specimenId
        - taxaClass
      type: object
      properties:
        prefix:
          type: string
          example: wuAreMari
        publicName:
          type: string
          example: wuAreMari1
        species:
          type: string
          example: Arenicola marina
        taxonomyId:
          type: integer
          example: 6344
        specimenId:
          type: string
          example: SAN0000100
        commonName:
          type: string
          example: lugworm
        genus:
          type: string
          example: Arenicola
        family:
          type: string
          example: Arenicolidae
        order:
          type: string
          example: Capitellida
        taxaClass:
          type: string
          example: Polychaeta
        phylum:
          type: string
          example: Annelida
        kingdom:
          type: string
          example: Metazoa
      example:
        commonName: lugworm
        publicName: wuAreMari1
        phylum: Annelida
        kingdom: Metazoa
        species: Arenicola marina
        genus: Arenicola
        prefix: wuAreMari
        taxonomyId: 6344
        specimenId: SAN0000100
        taxaClass: Polychaeta
        family: Arenicolidae
        order: Capitellida
    Species:
      required:
        - commonName
        - family
        - genus
        - order
        - phylum
        - kingdom
        - prefix
        - species
        - taxonomyId
        - taxaClass
      type: object
      properties:
        prefix:
          type: string
          example: wuAreMari
        species:
          type: string
          example: Arenicola marina
        taxonomyId:
          type: integer
          example: 6344
        commonName:
          type: string
          example: lugworm
        genus:
          type: string
          example: Arenicola
        family:
          type: string
          example: Arenicolidae
        order:
          type: string
          example: Capitellida
        taxaClass:
          type: string
          example: Polychaeta
        phylum:
          type: string
          example: Annelida
        kingdom:
          type: string
          example: Metazoa
      example:
        commonName: lugworm
        phylum: Annelida
        kingdom: Metazoa
        species: Arenicola marina
        genus: Arenicola
        prefix: wuAreMari
        taxonomyId: 6344
        taxaClass: Polychaeta
        family: Arenicolidae
        order: Capitellida    
    ErrorMessageList:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorMessage'
    ErrorMessage:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          example: "Something has gone wrong"
      example:
        message: "Something has gone wrong"
  securitySchemes:
    ApiKeyAuth:        # name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: api-key    # name of the header, query parameter or cookie
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.apikey_auth
# security:
#   - ApiKeyAuth: []     # 2) Apply the API key globally to all operations
  